FROM node:18-alpine3.18
# Installing libvips-dev for sharp Compatibility
RUN apk update && apk add --no-cache build-base gcc autoconf automake zlib-dev libpng-dev nasm bash vips-dev git
# 환경변수 설정
# ARG NODE_ENV=development
ENV NODE_ENV=development

# opt 경로에 종속성 설치
WORKDIR /opt
COPY package.json yarn.lock ./
RUN yarn global add node-gyp
RUN yarn config set network-timeout 600000 -g && yarn install

# 앱 경로에 소스코드 복사
# 자연스럽게 상위 경로에 있는 node_modules 이용


EXPOSE 1337
CMD ["yarn", "develop"]
