services:
  strapi:
    build: 
      context: .
      dockerfile: Dockerfile.prod
    env_file: .env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      APP_KEYS: ${APP_KEYS}
    volumes:
      - ./.tmp:/opt/.tmp
  
    ports:
      - "1337:1337"
    
