services:
  strapi:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    env_file: .env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      APP_KEYS: ${APP_KEYS}
    volumes:
      - .:/opt/app
      - /opt/app/node_modules
    ports:
      - "1337:1337"
    # entrypoint: entrypoint.sh

